# Sampling

When we have a question about a certain population (an entire group of
individuals). Ideally we would ask them all (take a **census**). But
contacting every member of a population often isn't very practical: it
would take too much time and cost too much money. Instead, we put the
question to a **sample**, or subset of individuals of the population
from which we actually collect data, chosen to represent the entire
population.

When you want to identify the population, ask yourself, what does the
question want to know about? What group of people does the
question/problem address?

When identifying the sample, ask yourself, what group does the work done
actually address?

## Bias

When we collect data, there is the possibility of the data becoming
systematically pushed towards a specific outcome. For example, if we
want to learn about the GPA average in the school and take a sample of
students only from a class, it's quite possible that the sample is not
representative of the school. We will probably result in a GPA average
that is higher or lower than the actual GPA average in the school. There
are several ways that this can happen. The main way that we learn are:

### Response Bias

Response bias is created when something causes people’s responses to be systematically pushed in one direction.  

### Non-response Bias

Nonresponse occurs when an individual chosen for the sample can’t be contacted or refuses to participate

### Undercoverage

Undercoverage occurs when some members of the population cannot be chosen in the sample. 

### Voluntary Response Sample

Voluntary response samples consists of people who choose themselves by responding to general invitation, causing the chosen sample to not be representative of the population

### Convenience Sample

Choosing individuals from a population who are easy to reach results in a convenience sample.

## Sampling Methods

### Simple Random Sample (SRS)

In a SRS, each individual (the words) and each subgroup of individuals has the same chance of being chosen from the population of all words in the song. 

### Stratified Random Sample

In a stratified random sample, we first determine **strata** within our population. You can think of strata as subgroups of people that we divide based on the type/status of the things that we are sampling. The goal of the random sample is then to take an SRS from each strata (normally, you want the same amount of people from each stratum).

### Random Cluster Sample

In a random cluster sample, we first determine **clusters** within our population. You can think of clusters as subgroups of people that we divide based on the location of the things that we are sampling (there should be no way to distinguish between the clusters besides  where they are). The goal of the random sample is then to take select random clusters and then sample all people in the chosen clusters.

### Systematic Random Sample

In a systematic random sample, we randomly choose an interval (n) and/or a starting point at which to select individuals and then we select every nth individual.
