# Sampling Distributions

Sampling Distribution
: A sampling distribution is the distribution of values taken by a sample statistic (a sample mean or sample proportion) in *all possible samples of a given size $n$* from the same population. 

Unbiased Estimator
: A statistic used to estimate a parameter is an \textbf{unbiased estimator} if the mean of its sampling distribution is equal to the true value of the parameter being estimated.
: Not all statistics are unbiased estimators and the data that we collect always has to follow a random process that is representative of the population.

Variability of a Statistic
: The variability of a statistic is described by the spread of its sampling distribution. 
: This spread is determined mainly by the size of the random sample. Larger samples give smaller spreads. The spread of the sampling distribution does not depend much on the size
of the population, as long as the population is at least 10 times larger than the sample ([10\% Condition](#ten-per-cond)).

## Sampling Distribution of $\hat p$

::: {.highlight}
Choose an SRS of size $n$ from a population of size $N$ with proportion $p$ of successes. Let $\hat p$ be the sample proportion of success. Then:

- The mean of the sampling distribution of $\hat p$ is $$\mu_{\hat p} = p$$

- The standard deviation of the sampling distribution of $\hat p$ is  $$\sigma_{\hat p} = \frac{\sigma_p}{\sqrt{n}} = \sqrt{\frac{p(1-p)}{n}}$$ as long as the [10\% condition](#ten-per-cond) is satisfied.

- As $n$ increases, the sampling distribution of $\hat p$ becomes approximately Normal. Before you perform calculations, check that the [Large Counts condition](#large-counts-cond) is satisfied: 

\begin{equation}
np \geq 10 \text{ and }n(1-p) \geq 10
\end{equation}

:::

## Sampling Distribution of $\bar x$

::: {.highlight}
Suppose that $\bar x$ is the mean of an SRS of size $n$ drawn from a large population with mean $\mu_X$ and standard deviation $\sigma_X$. Then: 

- The mean of the sampling distribution of $\bar x$ is $$\mu_{\bar x} = \mu_X$$

- The standard deviation of the sampling distribution of $\bar x$ is $$\sigma_{\bar x} = \frac{\sigma_X}{\sqrt{n}}$$ as long as the [10\% condition](#ten-per-cond) is satisfied.

\* These facts about the mean and standard deviation of $\bar x$ are *true no matter what shape the population distribution has.*
:::

### Normal/Large Condition for $\bar x$ {#large-cond}
::: {.highlight}
If the population distribution is Normal, then so is the sampling distribution of $\bar x$. This is true no matter what the sample size $n$ is.

If the population distribution is not Normal, the sampling distribution of $\bar x$ will be approximately Normal in most cases if $n \geq 30$. This fact is justified by the [Central Limit Theorem](#clt).
:::

### Central Limit Theorem (CLT) {#clt}

::: {.highlight}
If you have a population with mean $\mu$ and standard deviation $\sigma$ and take sufficiently large random samples from the population with replacement, then the distribution of the sample means will be approximately normal distributed.

\* This allows us to use Normal probability calculations to answer questions about sample means/proportions from many observations even when the population distribution is not Normal
:::

### When do we have normality?

| Shape of Population Distribution | Minimum Sample Size ($n$) needed to achieve an approximately normal $\bar x$ sampling distribution |
|-------------------------------------------|----------------------------------------------------------------------------------------------------|
| Approximately Normal                      | 1                                                                                                  |
| Slightly non-normal                       | Somewhere between 10-30, depending on how “slightly” non-normal                                    |
| Very non-normal, skewed                   | About 30                                                                                           |
