# Chi-Squared Tests

$\chi^2$ (pronounced "kai" squared) tests are used in situations where we have 2 or more proportions, and we want to see whether the distribution of those proportions is something that could occur naturally. There are three types that we cover.

## Sampling distribution of $\chi^2$

The sampling distribution of $\chi^2$ is not a Normal distribution. It is a right-skewed distribution that allows only positive values because $\chi^2$ can never be negative.
When the expected counts are all at least 5, the sampling distribution of the $\chi^2$ statistic is close to a $\chi^2$ distribution with a degrees of freedom based off the test that we do.
The $\chi^2$ distributions are a family of distributions that take only positive values and are skewed to the right. A particular chi-square distribution is specified by giving its degrees of freedom.

```{r ChiSq df plot}
library(ggplot2)

ggplot() +
    xlim(0, 17) + ylim(0,.25) +
    stat_function(aes(color = "df = 1"), fun = dchisq, 
                  args = list("df" = 1), size = 1.2, n = 1000) + 
    stat_function(aes(color = "df = 4"), fun = dchisq, 
                  args = list("df" = 4), size = 1.2, n = 1000) + 
    stat_function(aes(color = "df = 8"), fun = dchisq, 
                  args = list("df" = 8), size = 1.2, n = 1000) + 
    theme_minimal() + theme(legend.position = c(0.8, 0.8)) +
    labs(color = expression(paste(chi^2, " distribution with")), 
         x = expression(chi^2),
         y = "Density")
```

## Conditions {#ChiSqCond}

::: {.highlight}
- **Random:** The data comes from a well-designed random sample or from a randomized experiment.

- **10%:** When sampling without replacement, check that $n\leq(.10)N$

- **Large Counts:** All expected counts are greater than 5
:::

<details>
<summary> Be careful and remember that: </summary>

- The chi-square test statistic compares observed and expected counts. Don’t try to perform calculations with the observed and expected proportions in each category.

- When checking the Large Sample Size condition, be sure to examine the expected counts, not the observed counts.
</details>

## Chi-Squared Goodness-of-Fit {#ChiSqGOF}

::: {.highlight}
We do this test when we wonder, "Does this data fit with what they are saying?" So how "good" does the distribution of data that we see "fit" with the distribution that they claim?
:::

**Hypotheses:**

$H_0$: The stated distribution of the categorical variable in the population of interest is correct.
$$H_0:p_1=p_{0_1},p_2=p_{0_2}, \cdots ,p_c=p_{0_c} $$
where there are $c$ categories in the categorical variable

$H_a$: The stated distribution of the categorical variable in the population of interest is not correct
$$H_a:p_1 \not = p_{0_1},p_2 \not = p_{0_2}, \cdots ,p_c \not = p_{0_c}$$

**Expected Counts:**

The expected count for each category ($E_i$) is the sample size ($n$) times the stated probability of the category $p_{0_i}$.
$$E_i=np_{0_i}$$

**Degrees of freedom:**

We calculate the degrees of freedom by taking the # of categories - 1
$$df=c-1$$

**Chi-Square Test Statistic:**
$$\chi^2=\sum\frac{(Observed-Expected)^2}{Expected} = \sum\frac{(x_i-E_i)^2}{E_i}$$

## Chi-Squared Test of Homogeneity {#ChiSqHomogen}

::: {.highlight}
We do this test when we wonder, "Is the distribution of this group's data the same as this other group's distribution of data?" So how similar ("homogenous") is one group/treatment compared to another?
:::

<!-- Hypotheses:  -->
<!-- $H_0$: The distribution of the variable is the same across all groups/treatments. -->

<!-- $H_a$: There is at least some difference between the distribution of the variable across the groups/treatments -->

<!-- Expected Counts: -->
<!-- The expected count for each category ($E_i$) is the sample size ($n$) times the stated probability of the category $p_{0i}$. -->
<!-- $$E_i=np_{0i}$$ -->

<!-- Degrees of freedom:  -->
<!-- We calculate the degrees of freedom by taking the # of categories - 1 -->
<!-- $$df=c-1$$ -->

<!-- Chi-Square Test Statistic:  -->
<!-- $$\chi^2=\sum\frac{(Observed-Expected)^2}{Expected} = \sum\frac{(x_i-E_i)^2}{E_i}$$ -->

## Chi-Squared Test of Independence {#ChiSqInd}

::: {.highlight}
We do this test when we wonder, "Are these two variables in this set of data independent or not?" In other words, this is a more deterministic way of doing what we did in [Chapter 6][Probability]
when we compared just the probability of a single event and a conditional probability
:::
