# From Value to Probability

## z statistics/score

If you are given a z-score of $z$ and the range that you want a corresponding area (probability) that you want to find, there are normally two situations, one where you want the area to the left of $z$ (i.e. $P(Z < z)$) and the area to the right of $z$ (i.e. $P(Z > z)$). 

### $P(Z < z)$

If you want the area to the left of $z$, you look up the z-score in [Table A](#table-a) by finding the corresponding whole number and tenths place on the left margin and the corresponding hundreths place on the top margin of the table then right down the number that you find.

For example, $P(Z < -1.01) = 0.1562$

You can also use the calculator and do `normalcdf(-1000, -1.01)`, where `-1000` represents $- \infty$ since you want the area from $- \infty$ to -1.01. The calculator needs the lower bound and upper bound of the area that you want to find.

### $P(Z > z)$

If you want the area to the right of $z$, you **first** look up the z-score in [Table A](#table-a) by finding the corresponding whole number and tenths place on the left margin and the corresponding hundreths place on the top margin of the table. Take note of the probability that you found, then take the complement of that probability by subtracting from 1.

For example, $P(Z > 1.01) = 1 - P(Z < 1.01) = 1 - 0.8438 = 0.1562$

This is an application of the [complement rule][Complement Rule], where $P(Z > z)^C = P(Z < z)$ and thus $P(Z > z) = 1 - P(Z < z)$.

You can also use the calculator and do `normalcdf(1.01, 1000)`, where `1000` represents $\infty$ since you want the area from 1.01 to $\infty$.

### $P(z_1 < Z < z_2)$

Say you want the area between two z-scores/statistics, $z_1$ and $z_2$, then you do the same thing by looking up the z-scores on the tables as described above and subtract the probability that you find for $z_2$ from the one that you find for $z_1$.

For example, $$P(-1.01 < Z < 1.01) = P(Z < 1.01) - P(Z < -1.01) = 0.8438 - 0.1562 = 0.6876$$

On the calculator, you can do `normalcdf(-1.01, 1.01)`

## t statistics/score

If you are given a t-statistic of $t$ and the range that you want a corresponding area (probability) that you want to find, there are normally two situations, one where you want the area to the left of $t$ ($P(t_{n-1} < t)$) and the area to the right of $t$ ($P(t_{n-1} > t)$). Where $t_{n-1}$ represents the t-distribution with degrees of freedom $df = n-1$. For all of these, calculate the degrees of freedom first.

To do this, take a look at [Table B](#table-b).

Table B only provides the right tail of corresponding to $|t|$.

Table B's left margin describes the degrees of freedom that you have. Since we know that the [t-distribution is conservative](#t-justification), **if your degrees of freedom is not on the margin, round your degrees of freedom down to the nearest one**.

The top margin describes the probability that corresponds to the right of $|t|$.

The table itself contains the various exact $t$ statistics for the corresponding probability and degrees of freedom.

With this context, since we know that the t-distribution is symmetrical, all we need to do is look up our value of $|t|$ in the middle of Table B and write down the corresponding probability

### Examples

- $P(t_{29} < -1.2)$
    - Look up the $|t| = |-1.2| = 1.2$ since $P(t_{29} < -1.2) = P(t_{29} > 1.2)$
    - At the row with $df = 29$, notice that $1.055 < 1.2 < 1.311$
    - These values correspond to probability of $0.15$ and $0.10$ respectively.
    - This means that $0.10 < P(t_{29} < -1.2) < 0.15$
    - This is the only answer that we know from the table, the probability is between 0.10 and 0.15.
    - **Alternatively**, use the calculator command `tcdf(-1000, -1.2, 29)`, where we put the lower bound, upper bound, and the degrees of freedom respectively.
    
- $P(t_{57} > 1.2)$
    - Round your degrees of freedom down to 50, since it's the next lowest one. $df = 57 \sim 50$.
    - At the row with $df = 50$, notice that $1.047	< 1.2 < 1.299$
    - These values correspond to probability of $0.15$ and $0.10$ respectively.
    - This means that $0.10 < P(t_{57} > 1.2) < 0.15$
    - This is the only answer that we know from the table, the probability is between 0.10 and 0.15.
    - **Alternatively**, use the calculator command `tcdf(1.2, 1000, 57)`, where we put the lower bound, upper bound, and the degrees of freedom respectively.

