# Critical Values

## From Confidence Level to $z^*$

When constructing confidence intervals, we need the value $z^*$ such that $C$% of the estimated sampling distribution is between $-|z^*|$ and $|z^*|$. In other words, imagine:

```{r Conf level on normal dist, warning = FALSE}
library(ggplot2)

ggplot() + xlim(-4,4) +
    geom_polygon(aes(x = c(-2, seq(-2,2,0.01), 2), 
                     y = c(0, dnorm(seq(-2, 2, 0.01)), 0)), 
                 alpha = 0.5) +
    stat_function(fun = dnorm, size = 1.2, n = 1000) + theme_void() +
    annotate("segment", x = -2, xend = -2, y = -.01, yend = .01, size = 1.1) + 
    annotate("text", x = -2, y = -.025, label = expression(paste('-|', z^'*', '|'))) +
    annotate("segment", x = 2, xend = 2, y = -.01, yend = .01, size = 1.1) + 
    annotate("text", x = 2, y = -.025, label = expression(paste('|', z^'*', '|'))) +
    annotate("segment", x = -2.5, y = .2, xend = -1.5, yend = .05, arrow = arrow(), size = 1.1) +
    annotate("text", x = -2.5, y = 0.225, label =  "Confidence Level C")
```

So if we want to $z$ that corresponds to the confidence level, we have to determine the area of the left/right tail that corresponds to the confidence level. We know that if there's $C$% in the middle, then there's $100\% - C$ left in the two tails. For one tail, that'll be $\frac{100\% - C}{2}$.

Look up that proportion in [Table A](#table-a) in the middle of the table, take the larger value if it's not on there specifically, and back track to the margins to get your desired value of $z^*$.

The sign of any critical value does not matter, so just take the absolute value as your critical value.

### Examples

- 90% confidence
    - Find that the area that we want is: $\frac{100\% - 90%}{2} = 5\% = 0.05$
    - Try to find 0.05 in the middle of Table A and you notice that it is between 0.0505 and 0.0495.
    - Take the larger value, 0.0505 and look at the margins for the $z$ that corresponds to it, -1.64.
    - Just take the positive value, $z^* = 1.64$.
    - **Alternatively,** do the calculator command `invNorm(0.05)` to get a value of around -1.64. Take the positive value as your critical value, $z^* = 1.64$.
    
- 99% confidence
    - Find that the area that we want is: $\frac{100\% - 99%}{2} = 0.5\% = 0.005$
    - Try to find 0.005 in the middle of Table A and you notice that it is between 0.0051 and 0.0049.
    - Take the larger value, 0.0051 and look at the margins for the $z$ that corresponds to it, -2.57.
    - Just take the positive value, $z^* = 2.57$.
    - **Alternatively,** do the calculator command `invNorm(0.005)` to get a value of around -2.5758. Take the positive value as your critical value, $z^* = 2.58$.

## From Confidence Level and df to $t^*$

The same principles for $z^*$ applies to $t^*$, except we have to use degrees of freedom too.

[Table B](#table-b) conveniently has a confidence level margin at the bottom of the table, which corresponds to the tail probability that's given in the top margin of the table.

The left margin is where you should look for the degrees of freedom, calculated by $df = n-1$. 

Find the critical value by: looking up the degrees of freedom and the confidence level in the left margin and bottom margin respectively. Round the degrees of freedom down (as mentioned in the [previous section][t statistics/score]). The critical value is the number that you pinpoint in the middle of the table.

### Examples

- 90% confidence and 24 degrees of freedom
    - Look at the $df = 24$ row and the confidence level 90% column.
    - Take the value in the middle of the table that you pinpoint from that row and column, $t^* = 1.711$
    
- 99% confidence and 96 degrees of freedom
    - Round your df down to the next available value. $df = 96 \sim 80$.
    - Look at the $df = 80$ row and the confidence level 99% column.
    - Take the value in the middle of the table that you pinpoint from that row and column, $t^* = 2.639$
