# Basic Notation

## Lists

Most of the time, you will see $x$ denote a list of values (i.e. a
variable in a data table).

For example, if $x$ was the list of numerical values $a$ to $g$, we can
write it as:

$x = [a, b, c, d, e, f, g]$

Then, $x_i$ means the $i^{th}$ value in the list of $x$, so

$x_1 = a$ and $x_2 = b$ and $x_7 = g$.

## $n$

In regards to a data table or list of values, $n$ stands for the number
of rows or data points that are in the data table or list (we will learn
this as the *sample size* later on)

So, for list $x$, $n = 7$.

Adding on, $x_n$ would mean the last value in the list $x$ (since there
are only $n$ values in $x$)

## Summation ($\Sigma$)

You will also see the greek letter $\Sigma$ in formulas. Usage of this
sign means that we are using *summation notation*.

If we want the sum of all numbers from 1 to 7, we would write it as,

$$\sum_{i=1}^7 i$$

We interpret this as,

1.  Start from $i = 1$, evaluate the expression, which is $i$.

2.  Keep our evaluated expression to the side and get ready to add the
    other values to it, so

$$1 + \cdots$$

3.  Now go the next numbers until we get to $7$ (the number on the top
    of the $\Sigma$) So moving onto $i = 2$, we end up with
    $$1 + 2 + \cdots$$ \newline And with $i = 3$, we end up with
    $$1 + 2 + 3 + \cdots$$ \newline

4.  When we get to the end of it (when we reach $i = 7$), we have the
    *expanded form* of the summation. $$1 + 2 + 3+ 4 + 5 + 6 + 7$$

## Other notation

-   $\bar x$: The "line" on top of $x$ means the *mean of* $x$. If we
    had $\bar a$, I would be asking for the mean of $a$.
    -   Pronounced "x bar"
-   $\hat p$: The "hat" on top of $p$ means the *estimate of* $p$. If we
    had $\hat x$, I would be asking for the estimate of $x$.
    -   Pronounced "p hat"

## Other commonly used symbols

-   $N$: population size
-   $p$: proportion, probability, or p-value
-   $\mu$: population mean (true mean)
-   $\bar x$: sample mean
-   $\sigma$: population standard deviation (true standard deviation)
-   $s_x$: sample standard deviation (of x), so $s_y$ is the sample
    standard deviation of $y$
-   $SE_{\bar x}$: Standard error of the sample mean (of x), the estimate of the standard deviation of the sample mean.





