# $t^\ast$ Critical Values

The same principles for $z^\ast$ applies to $t^\ast$, except we have to use degrees of freedom too.

``` {ojs t star critical val demo}

function t_df(from, to, df) {
    var x = d3.range(from, to + 0.005, 0.01);
    var result = [];
    x.forEach((val, i) => {
        result.push({"x": val, "y": jStat.studentt.pdf(val, df), "lab": "t distribution with df = " + df + " degrees of freedom"});
    })
    return result;
}

function t_critical_val(C, df) {
    var val = jStat.studentt.inv((100 - C) / 2 / 100, df);
    return [val, -1 * val]
}

function t_conf_region(C, df) {
    var cutoffs = t_critical_val(C, df);
    var x = d3.range(cutoffs[0], cutoffs[1] + 0.005, 0.01);
    var result = [];
        x.forEach((val, i) => {
        result.push({"x": val, "y": jStat.studentt.pdf(val, df), "lab": "t distribution with df = " + df + " degrees of freedom"});
    });
    return result;
}

Plot.plot({
  marks: [
    Plot.areaY(t_conf_region(C2, df),
      {
        x: "x", 
        y: "y",
        fillOpacity: 0.3
      }
    ),
    Plot.line(t_df(-4, 4, df),
      {
        x: "x", 
        y: "y",
        stroke: "lab",
        strokeWidth: 3
      }
    ),
    Plot.ruleX([t_critical_val(C2, df)[0]]),
    Plot.ruleX([t_critical_val(C2, df)[1]]),
    Plot.text([{"x": t_critical_val(C2, df)[0] + 0.4, "y": 0.35}, {"x": t_critical_val(C2, df)[1] - 0.4, "y": 0.35}], {x: "x", y:"y", text: ["-|t*| = " + t_critical_val(C2, df)[0].toFixed(2), "|t*| = " + t_critical_val(C2, df)[1].toFixed(2)]})
  ],
    
    x: { label: "t" },
    y: {domain: [0, .41],
    label: "Density"},
    color: {
        legend: true
    },
    caption: "t distribution with df = " + df + " degrees of freedom"
})

viewof df = Inputs.range(
[1, 100],
{value: 3, step: 1, label: "Degrees of Freedom (df):"}
)

viewof C2 = Inputs.range(
[1, 99.99],
{value: 95, step: 0.01, label: "Confidence Level:"}
)

```



[Table B](#table-b) conveniently has a confidence level margin at the bottom of the table, which corresponds to the tail probability that's given in the top margin of the table.

The left margin is where you should look for the degrees of freedom, calculated by $df = n-1$.

Find the critical value by: looking up the degrees of freedom and the confidence level in the left margin and bottom margin respectively. Round the degrees of freedom down. The critical value is the number that you pinpoint in the middle of the table.

<details>
<summary> Why round down? </summary>

By rounding the degrees of freedom down, you use a more conservative estimate. 

[The main reason that we are even using the $t$-distribution is because it is more conservative than the Normal distribution](#t-justification). 

By rounding the degrees of freedom down, you use a more conservative $t$-distribution (more area in the tails), so you ensure that you do not underestimate your answer, rather, you purposely overestimate your answer.

</details>

## Examples

- 90% confidence and 24 degrees of freedom

> Look at the $df = 24$ row and the confidence level 90% column.
>
> Take the value in the middle of the table that you pinpoint from that row and column, $t^\ast = 1.711$

- 99% confidence and 96 degrees of freedom

> Round your df down to the next available value. $df = 96 \sim 80$.
> 
> Look at the $df = 80$ row and the confidence level 99% column.
> 
> Take the value in the middle of the table that you pinpoint from that row and column, $t^\ast = 2.639$
